meta_product_name: "Tip-a-Trip"
meta_title: "Tip-a-Trip - Create | Share | Travel"
meta_description: "Build your holiday itinerary with Tip-A-Trip"
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@tip_a_trip"   # required for Twitter Cards
